### PR TITLE
Get rid of the 8.3 trick to address issue #61

### PR DESCRIPTION
**Pull request by vds2212**
Hi Christian,

Here are the changes I propose to get rid of the 8.3 trick that strip part of the path.

Remark: Unfortunately it does solves all my problems because to change `C:\Windows\System32\Drivers\etc\hosts` I need another user and to run in elevated mode and it seems that runas do only the first part and not the second.

Best regards,
Vivian.

### CODE REVIEW

**Comment by chrisbra** [comment]
okay thanks, that makes sense.

**Comment by chrisbra** [comment]
Yes, I don't know a way to make runas run in elevated mode.

**Comment by vds2212** [comment]
Thanks I'm fighting with Windows API. I know Notepad++ is doing it so it should be possible. Maybe should I have a look at the code of Notepad++.

**Comment by chrisbra** [comment]
yes, agree, that is one of the very nice features of Notepad++ would be great to have this in vim a well.

**Pull request merged**
