### PR TITLE
Check if BufWritePost autocommands exist

### PR DESCRIPTION
**Pull request by blueyed**
Fixes "No matching autocommands" message.

### CODE REVIEW

**Comment by blueyed** [comment]
Still triggers it with `-u NONE`, which results in those:

```
:au BufWritePost                                                                   
--- Autocommands ---
gzip  BufWritePost
    *.gz      call gzip#write("gzip")
    *.bz2     call gzip#write("bzip2")
    *.Z       call gzip#write("compress -f")
    *.lzma    call gzip#write("lzma -z")
    *.xz      call gzip#write("xz -z")
    *.lz      call gzip#write("lzip")
    *.zst     call gzip#write("zstd --rm")
```

**Comment by blueyed** [comment]
I guess this needs a `:silent` then?

**Comment by chrisbra** [comment]
yes, please add a `:sil` then.

**Comment by blueyed** [comment]
Amended.

**Pull request merged**
